### ISSUE TITLE
Issue with TCastleScrollView on Android

### ISSUE THREAD

**Issue by eugeneloza** [castle-engine/castle-engine#452]
So, I've ran into a strange issue with two instances of `TCastleScrollView` defined in a `castle-user-interface` get filled in `TCastleView.Start`. On Desktop (Linux, Windows) it works without any issues. However, on Android both are rendered as empty. As there is absolutely nothing platform-dependent in code that handles those, my biggest suspicion was that CGE tried to fill in `TCastleScrollView` before it was resized properly and it e.g. could have had zero or default size, which resulted in broken value of content position, e.g. `Scroll = infinity` or something like that. Following this assumption I've re-filled content right before showing the first frame and it worked (just re-filling content in Start several times didn't work), this is a workaround I've made:

https://gitlab.com/EugeneLoza/vinculike/-/commit/9217be465e180c009b81bc75f1a05038c8ae5cb7

I didn't make a deep investigation so far on the actual causes of the bug, nor made a "minimal reproduction" case. So either leaving here not to forget or maybe the assumption above could be enough to pin down the origin of the problem.

**Comment by michaliskambi** [comment]
Hm, unfortunately I don't have any guess, based on the description. The sizing algorithms are platform-independent, and even the initial order of events (window open, then first resize) is the same for both Android and desktops.

I'll need to see a testcase that reproduces this.

I did a quick test, filling 2 scroll views with 101 buttons from code in `TViewMain.Start`, and it seems to work fine -- both on desktop (Linux) and Android I see the same result. It's a rather standard usage of scroll view. I set `AutoSizeToChildren=true` on both `ScrollArea` instances.  As it happens 2 screenshots below look almost identical, as my Android tablet happens to have the same aspect ratio as my laptop screen :)

( Note: The performance on Android is alarmingly low. Though this is a cheap Android tablet, but displaying such simple UI should be faster. But this is unrelated to this issue. )

[my-new-project-testscrollview-0.1-src.zip](https://github.com/castle-engine/castle-engine/files/10809341/my-new-project-testscrollview-0.1-src.zip)

![Zrzut ekranu z 2023-02-23 01-19-33](https://user-images.githubusercontent.com/1076978/220794668-3a3133bf-665b-48d9-94a3-2fe9b2d465ae.png)

![Screenshot_20230223-012336_My New Project](https://user-images.githubusercontent.com/1076978/220795331-08989569-7735-4b97-b327-4563c1f02289.jpg)

**Comment by michaliskambi** [comment]
> ( Note: The performance on Android is alarmingly low. Though this is a cheap Android tablet, but displaying such simple UI should be faster. But this is unrelated to this issue. )

OK, this is somewhat solved by setting `B.Culling=true` on all buttons. This way buttons not in scroll view are not rendered. This brings FPS to 30-50. It's still not perfect -- for such simple UI, one would hope we just have 60 FPS, by default (without developer having to set `Culling`).

![Screenshot_20230223-015340_My New Project](https://user-images.githubusercontent.com/1076978/220798494-06af7396-4957-4d34-b2dd-ea641d7f3099.jpg)

[my-new-project-testscrollview-0.1-src.zip](https://github.com/castle-engine/castle-engine/files/10809472/my-new-project-testscrollview-0.1-src.zip)

**Comment by michaliskambi** [comment]
Pinging @eugeneloza  about this -- we need a testcase to reproduce this :)

Also, you can retest with latest CGE. It is possible that the underlying issue was fixed with https://github.com/castle-engine/castle-engine/issues/458 , https://github.com/castle-engine/castle-engine/pull/459 .

**Comment by eugeneloza** [comment]
I don't know why GitHub didn't send me notificatios on the messages above. I'll have a look if the issue has been fixed, I saw that `TCastleScrollView` code has changed significantly (and somewhat broken my workaround for bottom-anchored scrollbars :)), but I didn't look into it in more details yet.

**Comment by eugeneloza** [comment]
No, the issue wasn't fixed with the latest CGE version, unfortunately. I still need to wait for before the first frame to see the contents of the scroll view.

**Comment by eugeneloza2factor** [comment]
For some reason thought this issue still waiting for testing - tested today, unfortunately still the same issue. I'll try to make a minimal reproduction asap.
